version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432"

  db_init:
    image: postgres:13
    container_name: postgres_init
    depends_on:
      - db
    entrypoint: [ "sh", "-c", "until pg_isready -h db -p 5432; do echo waiting for db; sleep 2; done; psql -h db -U ${DB_USER} -d postgres -c \"SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}' LIMIT 1\" | grep -q 1 || psql -h db -U ${DB_USER} -d postgres -c \"CREATE DATABASE ${DB_NAME}\"" ]
    environment:
      PGPASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    depends_on:
      - db
      - db_init
    ports:
      - "3000:3000"
    command: ["node", "dist/index.js"]

volumes:
  postgres_data:
