version: '3'
services:
  postgres_test:
    image: postgres:13
    container_name: test_pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
      POSTGRES_DB: ${DB_NAME_TEST}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
